#!/bin/sh
set -e

#DEBHELPER#

if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ]; then
    if [ -z "$DPKG_ROOT" ] && [ -d /run/systemd/system ]; then
        deb-systemd-invoke --user daemon-reload >/dev/null || true
        deb-systemd-invoke --user restart clockenstein-notification-agent.service >/dev/null || true
    fi
fi

exit 0
